"""empty message

Revision ID: 922456128fc4
Revises: 
Create Date: 2019-07-10 17:36:19.603168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922456128fc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('recover_hash', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recover_hash')
    # ### end Alembic commands ###
